In [1]:
import numpy as np


In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
#get dimensions
b.ndim

2

In [6]:
#get shape
b.shape

(2, 3)

In [7]:
#get type
a.dtype

dtype('int64')

In [10]:
#get size
b.itemsize

8

In [11]:
#get total size
a.nbytes

24

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
#get a specific element[r,c]
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
#get a specific column
a[:,2]

array([ 3, 10])

In [15]:
#getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [19]:
a[1,5]=20

a[:,2]= [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
* 3-d example

In [21]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##### initializing different types os arrays

In [23]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
#All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [26]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [27]:
#any other number(full_like)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [31]:
#random decimal numbers
np.random.rand(4,2)

array([[0.97472004, 0.87722905],
       [0.87116924, 0.3619834 ],
       [0.36492157, 0.84470949],
       [0.06875024, 0.20983548]])

In [34]:
#random integer values
np.random.randint(7, size=(3,3))

array([[1, 1, 4],
       [2, 0, 4],
       [5, 3, 2]])

In [35]:
# the identiy matrix 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [41]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### be careful when copying arrays!

In [47]:
a = np.array([1,2,3])
b = a.copy()
b[0] =100
print(a)


[1 2 3]


##### Mathematichs

In [48]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [49]:
a + 2

array([3, 4, 5, 6])

In [50]:
a - 2

array([-1,  0,  1,  2])

In [51]:
a * 2

array([2, 4, 6, 8])

In [52]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [57]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [54]:
a ** 2

array([ 1,  4,  9, 16])

In [55]:
#Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

##### Linear Algebra

In [58]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [59]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

##### Statistics

In [61]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.min(stats)

np.int64(1)

In [63]:
np.max(stats, axis=1)

array([3, 6])

In [64]:
np.sum(stats, axis=0)

array([5, 7, 9])

##### Reorganizing Arrays


In [65]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [67]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
#Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous

###### Load Data From File

In [71]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

##### Boolean Masking and Advanced Indexing


In [72]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])